name: BUild Release
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: ./release.sh

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: brightness
        path: ./build/release.out
